on: 
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  validate_canonical_match:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - run: make deploy-license-data
